version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=asdwqe
  backend:
    build: ./pythonweb
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./angularweb/angular-src/angular-app
    volumes:
      - .:/angular-app
    ports:
      - "80:80"
    